CREATE DATABASE IF NOT EXISTS SUPERHERO_DATABASE DEFAULT CHARACTER SET utf8;
USE SUPERHERO_DATABASE;

DROP TABLE if exists SUPERHEROES;
DROP TABLE if exists CITIES;
DROP TABLE if exists SUPERPOWERS;
DROP TABLE if exists AGGREGATE_SUPERHERODATA;


CREATE TABLE SUPERHEROES (	
	HERO_ID INTEGER NOT NULL,
	HERO_NAME VARCHAR(30), 
	REAL_NAME VARCHAR(30), 
	CREATION_YEAR INTEGER, 
	PRIMARY KEY (HERO_ID)
); 

CREATE TABLE CITIES(	
	CITY_ID INTEGER NOT NULL, 
	CITY_NAME VARCHAR(30), 
	PRIMARY KEY (CITY_ID)
);

CREATE TABLE SUPERPOWERS(	
	SUPERPOWER_ID INTEGER NOT NULL, 
	SUPERPOWER VARCHAR(30), 
	PRIMARY KEY (SUPERPOWER_ID)
);

CREATE TABLE AGGREGATE_SUPERHERODATA(
	HERO_ID INTEGER NOT NULL, 
	CITY_ID INTEGER NOT NULL, 
    SUPERPOWER_ID INTEGER NOT NULL,
    PRIMARY KEY (HERO_ID, CITY_ID, SUPERPOWER_ID)
    );
 

Insert into SUPERHEROES (HERO_ID, HERO_NAME, REAL_NAME,CREATION_YEAR) values (1,'SUPERMAN','CLARK KENT', 2000);
Insert into SUPERHEROES (HERO_ID, HERO_NAME, REAL_NAME,CREATION_YEAR) values (2,'SPIDERMAN','PETER PARKER', 1970);
Insert into SUPERHEROES (HERO_ID, HERO_NAME, REAL_NAME,CREATION_YEAR) values (3,'TAXMAN','MOGENS GLISTRUP', 1950);

insert into CITIES (CITY_ID, CITY_NAME) values (1,'New York');
insert into CITIES (CITY_ID, CITY_NAME) values (2,'Copenhagen');

insert into SUPERPOWERS (SUPERPOWER_ID, SUPERPOWER) values (1,'STRONG');
insert into SUPERPOWERS (SUPERPOWER_ID, SUPERPOWER) values (2,'WEB');
insert into SUPERPOWERS (SUPERPOWER_ID, SUPERPOWER) values (3,'TAX FRAUD');

insert into AGGREGATE_SUPERHERODATA (HERO_ID, CITY_ID, SUPERPOWER_ID) values (1,1,1);
insert into AGGREGATE_SUPERHERODATA (HERO_ID, CITY_ID, SUPERPOWER_ID) values (1,1,3);
insert into AGGREGATE_SUPERHERODATA (HERO_ID, CITY_ID, SUPERPOWER_ID) values (2,2,2);


commit;