-- Opgave A
SELECT * FROM SUPERHEROES;

-- Opgave B
SELECT * FROM SUPERHEROES
ORDER BY CREATION_YEAR DESC;

-- Opgave C
SELECT HERO_NAME, REAL_NAME FROM SUPERHEROES 
WHERE CREATION_YEAR = ( SELECT MAX(CREATION_YEAR) FROM SUPERHEROES );

-- Opgave D
SELECT HERO_NAME, CREATION_YEAR FROM SUPERHEROES
WHERE CREATION_YEAR > 1960;
-- Opgave E

-- Opgave F

-- Opgave G
SELECT SUPERHEROES.HERO_NAME, SUPERHEROES.REAL_NAME, AGGREGATE_SUPERHERODATA.SUPERPOWER_ID FROM AGGREGATE_SUPERHERODATA 
INNER JOIN SUPERHEROES ON AGGREGATE_SUPERHERODATA.HERO_ID=SUPERHEROES.HERO_ID;

-- Opgave H
SELECT CITY_NAME FROM CITIES ORDER BY CITY_NAME;

-- Opgave I
SELECT CITY_NAME FROM CITIES WHERE CITY_NAME LIKE 'C%';

-- Opgave J
SELECT SUPERHEROES.HERO_NAME, SUPERHEROES.REAL_NAME, AGGREGATE_SUPERHERODATA.SUPERPOWER_ID FROM AGGREGATE_SUPERHERODATA 
INNER JOIN SUPERHEROES ON AGGREGATE_SUPERHERODATA.HERO_ID=SUPERHEROES.HERO_ID;

-- Opgave K

-- Opgave L
